from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.common.exceptions import StaleElementReferenceException as SERE
from selenium.common.exceptions import NoSuchElementException as NSEE
from selenium.common.exceptions import TimeoutException as TE
import os
import pwinput
import instaloader
import time
import rich
from rich.console import Console
from rich.style import Style
from rich.progress import track
import subprocess
from datetime import datetime
now = datetime.now()
current_time = now.strftime("%H:%M:%S")
c = Console()



def cls():
    subprocess.call('cls', shell = True)
cls()

def Banner():
	c.print("[red] ============================================================")
	c.print("[red]||     ____                        __     ____        __    ||")
	c.print("[red]||    / __ \___  ____  ____  _____/ /_   / __ )____  / /_   ||")
	c.print("[red]||   / /_/ / _ \/ __ \/ __ \/ ___/ __/  / __  / __ \/ __/   ||")
	c.print("[red]||  / _, _/  __/ /_/ / /_/ / /  / /_   / /_/ / /_/ / /_     ||")
	c.print("[red]|| /_/ |_|\___/ .___/\____/_/   \__/  /_____/\____/\__/     ||")
	c.print("[red]||           /_/               v1.2.1                       ||")
	c.print("[red] ============================================================")
	c.print("[red] Designed And Managed By :- Department Of Cyber Affairs And Hacking")
Banner()                                         



def check():
	cmd = os.system('ping google.com -w 4 > clear')
	if cmd == 0:
		c.print("\n[green][", current_time, "[green]] Connected To The Internet")
	else:
		c.print("\n[green][", current_time, "[green]] [red]No Internet Connection")
		exit()
check()


def main():
	option = Options()
	option.add_argument('--headless')
	option.add_argument("--log-level=3")
	s = Service("chromedriver.exe")
	time.sleep(2)
	browser = webdriver.Chrome(service = s, options=option)
	browser.get("https://instagram.com/")
	c.print("\n[green][", current_time, "[green]] [dark_goldenrod]Suppressing Log Errors")
	c.print("\n\n[green][", current_time, "[green]] [dark_goldenrod]Starting Login Portal")
	time.sleep(3)
	username = browser.find_element(By.XPATH, "/html/body/div[1]/section/main/article/div[2]/div[1]/div[2]/form/div/div["
                                    "1]/div/label/input")
	browser.implicitly_wait(2)
	c.print("[green][", current_time,"[green]]", end = "")
	user = c.input("[purple4] Enter Your Username ---> ")
	lower = user.lower()
	username.send_keys(lower)
	time.sleep(2)
	password = browser.find_element(By.XPATH,
        "/html/body/div[1]/section/main/article/div[2]/div[1]/div[2]/form/div/div["
        "2]/div/label/input")
	c.print("[green][", current_time, "[green]] [purple4]Enter Your Password ---> ", end = "" )
	authkey = pwinput.pwinput(prompt = "", mask = "*")
	password.send_keys(authkey)
	time.sleep(2)
	c.print("\n[green][", current_time , "[green]] [dark_goldenrod]Attempting Login With \n [yellow1][+] Username : ", user, "\n[yellow1] [+] Password : ",authkey)
	login_button = browser.find_element(By.XPATH, "/html/body/div[1]/section/main/article/div[2]/div[1]/div[2]/form/div/div[3]")
	login_button.click()
	time.sleep(2)
	try:
		error = browser.find_element(By.ID, "slfErrorAlert")
		c.print("[green][", current_time, "[green]] [red] Check Your Username And Password")
		c.print("[green][", current_time, "[green]] Thanks For Using Report Bot (v1.2.1) \n\t\t\t ~ Designed By :- Department Of Cyber Affairs And Hacking")
		c.print("\n\n[dark_goldenrod][", current_time, "[dark_goldenrod]][dark_goldenrod] For Any Queries Text Us At Instagram :- dcahacking")
		exit()
	except NSEE:
		c.print("[green][", current_time, "[green]] Authentication Success")
	time.sleep(4)
	not_now = browser.find_element(By.XPATH, "/html/body/div[1]/section/main/div/div/div/div/button")
	not_now.click()
	time.sleep(4)
	search = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[1]/div/div/div/div[1]/section/nav/div[2]/div/div/div[2]/input")
	userid = c.input("\n\n[purple4]Enter The Username Of The Account To Be Reported ---> ")
	lower = userid.lower()
	search.send_keys(lower)
	time.sleep(4)
	browser.implicitly_wait(2)
	user_locked = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[1]/div/div/div/div[1]/section/nav/div[2]/div/div/div[2]/div[3]/div/div[2]/div/div[1]/div/a")
	user_locked.click()
	c.print("[green][", current_time, "[green]]", "[dark_goldenrod] Opening Profile")
	time.sleep(4)
	c.print("[green][", current_time, "[green]]", "[cyan1] Getting Ready For Reporting...")
	three_dots = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[1]/div/div/div/div[1]/section/main/div/header/section/div[1]/div/button")
	three_dots.click()
	time.sleep(4)
	report = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/button[3]")
	report.click()
	time.sleep(4)
	report_account = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/button[2]/div/div[1]")
	report_account.click()
	time.sleep(3)
	posting_content_voilation = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/button[1]")
	posting_content_voilation.click()
	time.sleep(3)
	c.print("[green][", current_time, "[green]]", "[dark_orange3] Starting Report Panel")
	c.print("\n\n[dark_red][1] It's spam")
	c.print("[dark_red][2] I just don't like it")
	c.print("[dark_red][3] Suicide, self-injury or eating disorders")
	c.print("[dark_red][4] Sale of illegal or regulated goods")
	c.print("[dark_red][5] Nudity or sexual activity")
	c.print("[dark_red][6] Hate speech or symbols")
	c.print("[dark_red][7] Violence or dangerous organizations")
	c.print("[dark_red][8] Bullying or harassment")
	c.print("[dark_red][9] Intellectual property violation")
	c.print("[dark_red][10] Scam or fraud")
	c.print("[dark_red][11] False information")

	options = int(c.input("\n[purple4]Enter The Violation Type Done By The Account Specified ---> "))

	if options == 1:
		c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under It's Spam")
		spam = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/button[1]")
		spam.click()
		time.sleep(2)
		close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
		close.click()
		c.print("[green][", current_time,"[green]]","[gold1] Report Success")
		c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")

	if options == 2:
		c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under I Just Don't Like It")
		dont_like = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/button[2]")
		dont_like.click()
		time.sleep(2)
		close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
		close.click()
		c.print("[green][", current_time,"[green]]","[gold1] Report Success")
		c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")

	if options == 3:
		c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Suicide, Self-Injury or Eating Disorders")
		ssoed = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/button[3]")
		ssoed.click()
		time.sleep(3)
		submit = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/button")
		submit.click()
		time.sleep(2)
		close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
		close.click()
		c.print("[green][", current_time,"[green]]","[gold1] Report Success")
		c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")

	if options == 4:
		c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Sale of Illegal or Regulated Goods")
		sirg = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/button[4]")
		sirg.click()
		time.sleep(3)
		c.print("[dark_red]\n[1] Fake health documents")
		c.print("[dark_red][2] Drugs")
		c.print("[dark_red][3] Firearms")
		c.print("[dark_red][4] Endangered animals")
		sub_opts = int(c.input("\n[purple4]Enter The Specification Of Your Report ---> "))
		if sub_opts == 1:
			c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Fake Health Documents")
			fhd = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/fieldset/div[1]/label")
			fhd.click()
			time.sleep(3)
			submit = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[6]/button")
			submit.click()
			time.sleep(2)
			close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
			close.click()
			c.print("[green][", current_time,"[green]]","[gold1] Report Success")
			c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")
		if sub_opts == 2:
			c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Drugs")
			drugs = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/fieldset/div[2]/label")
			drugs.click()
			time.sleep(3)
			submit = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[6]/button")
			submit.click()
			time.sleep(2)
			close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
			close.click()
			c.print("[green][", current_time,"[green]]","[gold1] Report Success")
			c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")
		if sub_opts == 3:
			c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Firearms")
			firearms = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/fieldset/div[3]/label")
			firearms.click()
			firearms.sleep(3)
			submit = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[6]/button")
			submit.click()
			time.sleep(2)
			close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[6]/button")
			close.click()
			c.print("[green][", current_time,"[green]]","[gold1] Report Success")
			c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")
		if sub_opts == 4:
			c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Endangered Animals")
			ea = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/fieldset/div[4]/label")
			ea.click()
			time.sleep(3)
			submit = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[6]/button")
			submit.click()
			time.sleep(2)
			close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
			close.click()
			c.print("[green][", current_time,"[green]]","[gold1] Report Success")
			c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")

	if options == 5:
		c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Nudity or Sexual Activity")
		nsa = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/button[5]")
		nsa.click()
		time.sleep(3)
		c.print("\n[dark_red][1] Nudity or pornography")
		c.print("[dark_red][2] Sexual exploitation or solicitation")
		c.print("[dark_red][3] Sharing private images")
		c.print("[dark_red][4] Involves a child")
		sub_opts = int(c.input("\n[purple4]Enter The Specification Of Your Report ---> "))
		if sub_opts == 1:
			c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Nudity or Pornography")
			nudity = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/fieldset/div[1]/label")
			nudity.click()
			time.sleep(3)
			submit = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[6]/button")
			submit.click()
			time.sleep(2)
			close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
			close.click()
			c.print("[green][", current_time,"[green]]","[gold1] Report Success")
			c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")
		if sub_opts == 2:
			c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Sexual Exploitation or Solicitation")
			ses = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/fieldset/div[2]/label")
			ses.click()
			time.sleep(3)
			submit = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[6]/button")
			submit.click()
			time.sleep(2)
			close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
			close.click()
			c.print("[green][", current_time,"[green]]","[gold1] Report Success")
			c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")
		if sub_opts == 3:
			c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Sharing Private Images")
			spi = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/fieldset/div[3]/label")
			spi.click()
			time.sleep(3)
			submit = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[6]/button")
			submit.click()
			time.sleep(2)
			close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
			close.click()
			c.print("[green][", current_time,"[green]]","[gold1] Report Success")
		if sub_opts == 4:
			c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Involves a Child")
			ichild = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/fieldset/div[4]/label")
			ichild.click()
			time.sleep(3)
			submit = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[6]/button")
			submit.click()
			time.sleep(2)
			close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
			close.click()
			c.print("[green][", current_time,"[green]]","[gold1] Report Success")
			c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")

	if options == 6:
		c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Hate Speech or Symbols")
		hss = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/button[6]")
		hss.click()
		time.sleep(3)
		submit = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/button")
		submit.click()
		time.sleep(2)
		close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
		close.click()
		c.print("[green][", current_time,"[green]]","[gold1] Report Success")
		c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")

	if options == 7:
		c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Violence or Dangerous Organizations")
		vdo = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/button[7]")
		vdo.click()
		time.sleep(3)
		c.print("[dark_red][1] Violent threat")
		c.print("[dark_red][2] Animal abuse")
		c.print("[dark_red][3] Death or severe injury")
		c.print("[dark_red][4] Dangerous organizations or individuals")
		sub_opts = int(c.input("\n[purple4]Enter The Specification Of Your Report ---> "))
		if sub_opts == 1:
			c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Violent Threat")
			vt = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/fieldset/div[1]/label")
			vt.click()
			time.sleep(3)
			submit = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[6]/button")
			submit.click()
			time.sleep(2)
			close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
			close.click()
			c.print("[green][", current_time,"[green]]","[gold1] Report Success")
			c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")
		if sub_opts == 2:
			c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Animal Abuse")
			aa = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/fieldset/div[2]/label")
			aa.click()
			time.sleep(3)
			submit = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[6]/button")
			submit.click()
			time.sleep(2)
			close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
			close.click()
			c.print("[green][", current_time,"[green]]","[gold1] Report Success")
			c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")
		if sub_opts == 3:
			c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Death or Severe Injury")
			dsi = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/fieldset/div[3]/label")
			dsi.click()
			time.sleep(3)
			submit = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[6]/button")
			submit.click()
			time.sleep(2)
			close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
			close.click()
			c.print("[green][", current_time,"[green]]","[gold1] Report Success")
			c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")
		if sub_opts == 4:
			c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Dangerous Organizations or Individuals")
			doi = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/fieldset/div[4]/label")
			doi.click()
			time.sleep(3)
			submit = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[6]/button")
			submit.click()
			time.sleep(2)
			close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
			close.click()
			c.print("[green][", current_time,"[green]]","[gold1] Report Success")
			c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")

	if options == 8:
		c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Bullying or Harassment")
		bh = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/button[8]")
		bh.click()
		time.sleep(3)
		c.print("[dark_red][1] Me")
		c.print("[dark_red][2] Someone I Know")
		c.print("[dark_red][3] Someone Else")
		sub_opts = int(c.input("\n[purple4]Who Is Being Bullied Or Harassed ---> "))
		if sub_opts == 1:
			c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Bullying or Harassment // Me")
			bhm = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/button[1]")
			bhm.click()
			time.sleep(3)
			submit = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/button")
			submit.click()
			time.sleep(2)
			close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
			close.click()
			c.print("[green][", current_time,"[green]]","[gold1] Report Success")
			c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")
		if sub_opts == 2:
			c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Bullying or Harassment // Someone I Know")
			bhsik = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/button[2]")
			bhsik.click()
			time.sleep(3)
			submit = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/button")
			submit.click()
			time.sleep(2)
			close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
			close.click()
			c.print("[green][", current_time,"[green]]","[gold1] Report Success")
			c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")
		if sub_opts == 3:
			c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Bullying or Harassment // Someone Else")
			bhse = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/button[3]")
			bhse.click()
			time.sleep(3)
			submit = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/button")
			submit.click()
			time.sleep(2)
			close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
			close.click()
			c.print("[green][", current_time,"[green]]","[gold1] Report Success")
			c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")

	if options == 9:
		c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Intellectual Property Violation")
		c.print("[red][+] You May Report This At :- https://help.instagram.com/535503073130320/")
		time.sleep(1.5)
		c.print("[green][", current_time,"[green]]","[gold1] Report Success")
		c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")

	if options == 10:
		c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under Scam or Fraud")
		sf = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/button[10]")
		sf.click()
		time.sleep(3)
		close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
		close.click()
		c.print("[green][", current_time,"[green]]","[gold1] Report Success")
		c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")

	if options == 11:
		c.print("[green][", current_time, "[green]]","[dark_goldenrod] Reporting Under False Information")
		fi = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/button[11]")
		fi.click()
		time.sleep(3)
		close = browser.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[4]/button")
		close.click()
		c.print("[green][", current_time,"[green]]","[gold1] Report Success")
		c.print("[green][", current_time, "[green]]", "[purple4] Updating Reports In Profile")
		c.print("[green][", current_time, "[green]] Thanks For Using Report Bot (v1.2.1) \n\t\t\t Designed By :- Department Of Cyber Affairs And Hacking")
		c.print("\n\n[dark_goldenrod][", current_time, "[dark_goldenrod]][dark_goldenrod] For Any Queries Text Us At Instagram :- dcahacking")

main()